version: '3.3'

services:
  minecraft:
    build: .
    volumes:
      - "/root/docker/minecraft-po3:/data"
    ports:
      - "25565:25565"
      - "25575:25575"
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Vancouver"
