version: '3.3'

services:
  minecraft:
    build: .
    volumes:
      - "/root/docker/minecraft-po3:/data"
    ports:
      - "25566:25566"
      - "25576:25576"
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Vancouver"
